version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localexample
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:localexample@mongo:27017/
      - MONGO_HOST=mongo
    ports:
      - "8080:8080"
    volumes:
      - ./user-service:/app
    command: ["./user-service"]

volumes:
  mongo_data: