version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localexample
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kong-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:localexample@mongo:27017/
      - MONGO_HOST=mongo
    ports:
      - "8080:8080"
    volumes:
      - ./user-service:/app
    command: ["./user-service"]
    networks:
      - kong-network

  kong:
    image: kong/kong-gateway:3.9-debian
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
    # command: "kong migrations up && kong start"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - kong-network

volumes:
  mongo_data:

networks:
  kong-network:
    driver: bridge
