# Kong JWT Plugin
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt
plugin: jwt
config:
  claims_to_verify:
    - exp

# JWT for User Service
---
apiVersion: v1
kind: Secret
metadata:
  name: note-app-user-service-jwt
  labels:
    konghq.com/credential: jwt
stringData:
  algorithm: HS256
  key: note-app-user-service
  secret: EFBF13B3-1D6F-4EF8-95FE-C71784B835F5
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: note-app-user-service
  annotations:
    kubernetes.io/ingress.class: kong
username: note-app-user-service
credentials:
  - note-app-user-service-jwt
