apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
  labels:
    app: note-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
        - name: note-service
          image: localhost/note-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: MONGO_URI
              value: "mongodb://root:localexample@mongo:27017"
            - name: NODE_ENV
              value: "production"
            - name: SERVICE_NAME
              value: "note-service"
            - name: JWT_SECRET
              value: "EFBF13B3-1D6F-4EF8-95FE-C71784B835F5"
---
apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  selector:
    app: note-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: note-service-route
  annotations:
    konghq.com/strip-path: "true"
spec:
  parentRefs:
    - name: kong
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /notes
      backendRefs:
        - name: note-service
          kind: Service
          port: 3000
