apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: localhost/user-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: MONGO_URI
              value: "mongodb://root:localexample@mongodb:27017/"
            - name: MONGO_HOST
              value: "mongodb"
            - name: JWT_ISSUER
              value: "note-app-user-service"
            - name: JWT_SECRET_KEY
              value: "EFBF13B3-1D6F-4EF8-95FE-C71784B835F5"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: user-service-route
  annotations:
    konghq.com/strip-path: "true"
spec:
  parentRefs:
    - name: kong
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /user-service/api/public
      backendRefs:
        - name: user-service
          kind: Service
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /user-service/api/private
      backendRefs:
        - name: user-service
          kind: Service
          port: 8080
