name: AFH - Deploy Frontend

on:
  workflow_dispatch:

permissions:
  id-token: write

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_STORAGE_ACCOUNT: afh
  CONTAINER_NAME: $web

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ls -la
            az storage blob upload-batch \
            --source ./azure-fundamental-handson/frontend \
            --destination ${{ env.CONTAINER_NAME }} \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login
