name: Terraform Provisioning for Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azure-fundamental-handson/infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Review
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: thai-nm
          minimum-approvals: 1
          issue-title: "Provisioning infrastructure"
          issue-body: "Please review Terraform plan."
          exclude-workflow-initiator-as-approver: false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
