name: Upload Frontend to Azure Blob Storage

on:
  workflow_dispatch:

env:
  AZURE_STORAGE_ACCOUNT: afh
  CONTAINER_NAME: $web

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
              --auth-mode login \
              --destination ${{ env.CONTAINER_NAME }} \
              --source ./frontend  
